### ISSUE TITLE
[13.0] duplicate key when renaming needaction_partner_ids to notified_partner_ids

### ISSUE THREAD

**Issue by sbidoul** [OCA/OpenUpgrade#2339]
Impacted versions: 13.0 (testing with all open 13.0 PR aggregated)

Steps to reproduce: Run openupgrade 8->9, 9->10, ..., 12-13.

Current behavior: 

In the 12->13 step:

```
bad query: 
            UPDATE ir_model_fields
            SET name = 'notified_partner_ids'
            WHERE name = 'needaction_partner_ids'
                AND model = 'mail.message'
            
ERROR: duplicate key value violates unique constraint "ir_model_fields_name_unique"
DETAIL:  Key (model, name)=(mail.message, notified_partner_ids) already exists.
```

This is apparently because `notified_partner_ids` was a thing in v8, then disappeared, then reappeared in v13.

Not sure if this is something I'm doing wrong (do I need to do some cleanup between steps?) or if it's something that has to / can be fixed. I can try to provide a fix if you think it's useful and give me a hint on how to approach this.

**Comment by pedrobaeza** [comment]
Indeed this kind of things can happen when you migrate in batch all versions. I suggest to patch this in openupgradelib catching that error and deleting the old row in that case, so we have a patch for all possible collisions.

**Comment by pedrobaeza** [comment]
I have implemented the suggestion in OCA/openupgradelib@38f0d13, but renaming instead of deleting, for being more conservative.

**Comment by pedrobaeza** [comment]
Another iteration has been needed in https://github.com/OCA/openupgradelib/commit/351034f8e18ff49768748c6995ad2137a3ac9b1a (+ a syntax fix) for fully handling this, but now tested and working.

**Comment by StefanRijnhart** [comment]
Working on an alternative fix as the previous fix would lead to dropping ir.property records if migration scripts were not careful and renamed the field twice (which is not unlikely for property fields, apparently). In the mean time, this particular case can be solved manually by removing the ir.model.fields record, and its ir.model.data entry manually before executing the 13.0 migration.

**Comment by FranciscoBigWings** [comment]
Hello. I am facing this error when upgrading from V12 to V13. Was this fixed through Openupgrade or should I manually remove the record as suggested above?

Thanks

**Comment by FranciscoBigWings** [comment]
Still getting this error saturday 27th. Impacted migration V12 to V13
- Original database is from V8 so I understand the error come from then.
- V12 is working stable in production enviroment since more than a year ago
- Update all to database V12 before migration to apply latest changes
- Using latest openupgradelib
- Pulling latest changes from OpenUpgrade V13
- Tried vacuumdb -f through postgres

Is this error widely fixed and I am the only one experiencing the error since latest commits?
